<img src="https://www.aseafi.es/wp-content/uploads/2020/09/Afi-Escuela.png" alt="Drawing" width="300"/>

# Introducción a Python


**Verónica Ruiz Méndez - Abril 2022**

Curso Introducción a Data Science - Afi Escuela de Finanzas

*Autor*: [Verónica Ruiz Méndez](https://www.linkedin.com/in/veronica-ruiz-mendez/) 

# Tipos de datos

<li>Cadenas de caracteres o <i>str</i>: Se especifican entre comillas simples, dobles o triples</li>
<li>Valores numéricos enteros o <i>int</i>: No incluyen punto decimal</li>
<li>Valores numéricos decimales o <i>float</i>: Incluyen punto decimal</li>
<li>Valores booleanos o <i>bool</i>: True / False (case sensitive)</li>


Para conocer el tipo de una variable se puede usar la función de Python <b>type</b>.

In [1]:
cadena = "Esto es una cadena"
type(cadena)

str

In [2]:
entero = 10
type(entero)

int

In [3]:
decimal = 10.1
type(decimal)

float

In [4]:
booleano = True
type(booleano)

bool

# Operadores básicos


Al igual que en otros lenguajes de programación tenemos un conjunto diverso de operadores para aplicar a variables y valores:

<li>Aritméticos: +, -, \*, /, \*\*, %, //</li>
<li>Lógicos: and, or, not</li>
<li>Comparativos: ==, !=, <>, >, <, >=, <=</li>
<li>Asignación: =, +=, -=. \*=, /=, \*\*=, %=, //=</li>
</ul>

# Secuencias

In [5]:
# Tuplas
tupla = (1, 2, 3, 4)
tupla

(1, 2, 3, 4)

In [6]:
# Listas
lista = [1, 2, 3, 4]
lista

[1, 2, 3, 4]

In [7]:
# Cadenas
string = "esto es una cadena"
string

'esto es una cadena'

# Numpy

Toda la libería de **NumPy** se articula alrededor de una única estructura de datos: la matriz multidimensional o ndarray (N-dimensional array).

In [8]:
import numpy as np

In [9]:
# Especificando dimensiones
array_unos = np.ones((2, 2))
array_unos

array([[1., 1.],
       [1., 1.]])

In [10]:
array_identidad = np.identity(3)
array_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
array.dtype

dtype('int64')

In [13]:
array.shape

(3, 4)

In [14]:
array + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [15]:
array - array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
array[2]

array([ 9, 10, 11, 12])

# Pandas

El pilar básico de la librería <b>pandas</b>, al igual que como ocurría con <b>numpy</b>, son las estructuras de datos que pone a nuestra disposición.<br/>
En este caso, dispondremos de dos estructuras de datos relacionadas, pero con su funcionamiento específico:<br/>
<ul>
<li><b>Series:</b> Para información unidimensional.</li>
<li><b>DataFrame:</b> Para información tabular.</li>
</ul>

Son estructuras muy similares a las ofrecidas por R: vectores (con nombre) y data.frame.

In [17]:
import pandas as pd

### Series

In [18]:
# Serie desde ndarray
array = np.array([2, 4, 6, 8, 10])
serie = pd.Series(array)
serie

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [19]:
serie.values

array([ 2,  4,  6,  8, 10])

In [20]:
serie.index

RangeIndex(start=0, stop=5, step=1)

In [21]:
serie = pd.Series(array, index=['a', 'b', 'c', 'd', 'e'])
serie

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [22]:
serie.values

array([ 2,  4,  6,  8, 10])

In [23]:
serie.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

### DataFrames

In [24]:
# DataFrame desde ndarray con índices para filas y columnas
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1', 'c2', 'c3', 'c4'])
dataframe

c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [25]:
dataframe.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
dataframe.index

Index(['f1', 'f2', 'f3', 'f4'], dtype='object')

In [27]:
dataframe.columns

Index(['c1', 'c2', 'c3', 'c4'], dtype='object')

In [28]:
dataframe['c1']

f1     0
f2     4
f3     8
f4    12
Name: c1, dtype: int64

In [29]:
dataframe.loc['f1']

c1    0
c2    1
c3    2
c4    3
Name: f1, dtype: int64