<img src="https://www.aseafi.es/wp-content/uploads/2020/09/Afi-Escuela.png" alt="Drawing" width="300"/>

# Numpy


**Verónica Ruiz Méndez - Septiembre 2022**

Curso Introducción a Machine Learning - Afi Escuela de Finanzas

*Autor*: [Verónica Ruiz Méndez](https://www.linkedin.com/in/veronica-ruiz-mendez/) 

Toda la libería de **NumPy** se articula alrededor de una única estructura de datos: la matriz multidimensional o ndarray (N-dimensional array).

Características de un ndarray:
- Un ndarray puede contener elementos de cualquier tipo.
- Todos los elementos de un ndarray deben tener el mismo tipo.
- El tamaño de un ndarray (númnero de elementos) se define en el momento de la creación y no puede modificarse.

In [2]:
import numpy as np

#### Creación de un ndarray

In [3]:
# Especificando dimensiones
array_unos = np.ones((2, 2))
array_unos

array([[1., 1.],
       [1., 1.]])

In [4]:
array_identidad = np.identity(3)
array_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Tipos de datos en ndarrays de NumPy

<ul>
<li><b>Enteros con signo:</b> np.int8, np.int16, np.int32 y np.int64</li>
<li><b>Enteros sin signo:</b> np.uint8, np.uint16, np.uint32 y np.uint64</li>
<li><b>Números en coma flotante:</b> np.float16, np.float32, np.float64, np.float128</li>
<li><b>Booleanos:</b> np.bool</li>
<li><b>Objetos:</b> np.object</li>
<li><b>Cadenas de caracteres:</b> np.string\_, np.unicode\_</li>
<li>...</li>
</ul>

In [6]:
array.dtype

dtype('int32')

#### Consulta de la composición de un ndarray

<ul>
<li><b>dtype</b>: Tipo del contenido del ndarray.</li>
<li><b>ndim</b>: Número de dimensiones/ejes del ndarray.</li>
<li><b>shape</b>: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones.</li>
<li><b>size</b>: Número total de elementos en el ndarray.</li>
</ul>

In [10]:
array.shape

(3, 4)

In [11]:
array.size

12

#### Operaciones aritméticas entre ndarrays

In [12]:
array + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [13]:
array - array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### Indexación 

In [18]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
array[1]

array([5, 6, 7, 8])

In [17]:
array[-1]

array([ 9, 10, 11, 12])