<img src="https://www.aseafi.es/wp-content/uploads/2020/09/Afi-Escuela.png" alt="Drawing" width="300"/>

# Regresión Logística


**Verónica Ruiz Méndez - Septiembre 2022**

Curso Introducción a Machine Learning - Afi Escuela de Finanzas

*Autor*: [Verónica Ruiz Méndez](https://www.linkedin.com/in/veronica-ruiz-mendez/) 

Importamos liberías a utilizar.

In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import numpy as np

Cargamos el set de datos.

In [2]:
X, y = load_iris(return_X_y=True)

In [3]:
X.shape

(150, 4)

In [4]:
y.shape

(150,)

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Definimos nuestro modelo de Regresión logística y entrenamos sobre nuestros datos.

In [7]:
clf = LogisticRegression(random_state=0, max_iter = 1000).fit(X, y)

In [8]:
clf.coef_

array([[-0.42380752,  0.96741082, -2.51696409, -1.07958084],
       [ 0.53446768, -0.32156715, -0.2063435 , -0.94451148],
       [-0.11066016, -0.64584367,  2.72330758,  2.02409232]])

In [9]:
clf.classes_

array([0, 1, 2])

Predecimos el valor que tomará un nuevo registro.

In [10]:
new = np.array([[5.1, 3.5, 1.4, 0.2]])

clf.predict(new)

array([0])

In [11]:
clf.predict_proba(new)

array([[9.81585954e-01, 1.84140314e-02, 1.44918429e-08]])